config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root 'static_pages#top'
  resources :users, only: %i[new create]
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  resources :travel_plans, only: %i[index new create show edit destroy update] do
    resources :tasks
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
  extend Enumerize
  enumerize :status, in: %i(pending working done)
  enumerize :baggage, in: %i(carry leave)

  validates :body, length: { maximum: 30 }
  validates :title, presence: true

  belongs_to :travel_plan
  belongs_to :user

  def self.ransackable_attributes(auth_object = nil)
    ["baggage", "body", "created_at", "due", "id", "status", "title", "travel_plan_id", "updated_at", "user_id"]
  end
end

app/models/travel_plan.rb
class TravelPlan < ApplicationRecord
  belongs_to :user
  has_many :tasks, dependent: :destroy

  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
  validates :name, presence: true, length: { maximum: 255 }
  validates :email, presence: true, uniqueness: true

  has_many :travel_plans, dependent: :destroy
  has_many :tasks, through: :travel_plans, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login

  add_flash_types :success, :danger
  
  private
  
  def not_authenticated
    redirect_to login_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_action :require_login, only: %i[top]

  def top; end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_travel_plan
  def index
    @q = @travel_plan.tasks.ransack(params[:q])
    @tasks = @q.result.page(params[:page]).order('created_at desc').per(10)
  end
  
  def new
    @task = @travel_plan.tasks.build
  end

  def create
    @task = @travel_plan.tasks.build(task_params)
    @task.user = current_user
    if @task.save
      redirect_to travel_plan_tasks_path(@travel_plan), success: t('tasks.create.success')
    else
      flash.now[:danger] = t('tasks.create.failure')
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @task = @travel_plan.tasks.find(params[:id])
  end

  def update
    @task = @travel_plan.tasks.find(params[:id])
    if @task.update(task_params)
      redirect_to travel_plan_tasks_path(@travel_plan), success: t('tasks.update.success')
    else
      flash.now[:danger] = t('tasks.update.failure')
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    task = @travel_plan.tasks.find(params[:id])
    task.destroy!
    redirect_to travel_plan_tasks_path, success: t('travel_plans.destroy.success')
  end

  private

  def task_params
    params.require(:task).permit(:title, :body, :status, :baggage, :due)
  end

  def set_travel_plan
    @travel_plan = current_user.travel_plans.find(params[:travel_plan_id])
  end
end

app/controllers/travel_plans_controller.rb
class TravelPlansController < ApplicationController
    def index
      @travel_plans = TravelPlan.where(user_id: current_user.id).includes(:user).order("created_at DESC").page(params[:page]).per(9)
    end

    def new
      @travel_plan = TravelPlan.new
    end

    def create
      @travel_plan = current_user.travel_plans.build(travel_plan_params)
      if @travel_plan.save
        redirect_to travel_plans_path, success: t('travel_plans.create.success')
      else
        flash.now[:danger] = t('travel_plans.create.failure')
        render :new, status: :unprocessable_entity
      end
    end

    def edit
      @travel_plan = current_user.travel_plans.find(params[:id])
    end
  
    def update
      @travel_plan = current_user.travel_plans.find(params[:id])
      if @travel_plan.update(travel_plan_params)
        redirect_to travel_plans_path(@travel_plan), success: t('travel_plans.update.success')
      else
        flash.now[:danger] = t('travel_plans.update.failure')
        render :edit, status: :unprocessable_entity
      end
    end
  
    def destroy
      travel_plan = current_user.travel_plans.find(params[:id])
      travel_plan.destroy!
      redirect_to travel_plans_path, success: t('travel_plans.destroy.success')
    end

    private

    def travel_plan_params
      params.require(:travel_plan).permit(:title, :country, :note, :due)
    end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: %i[new create]
  
  def new; end
  
  def create
    @user = login(params[:email], params[:password]) 
    if @user
      redirect_to root_path, success: t('user_sessions.create.success')
    else
      flash.now[:danger] = t('user_sessions.create.failure')
      render :new, status: :unprocessable_entity
    end
  end
  
  def destroy
    logout
    redirect_to root_path, status: :see_other, success: t('user_sessions.destroy.success')
  end
end
  

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: %i[new create]
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path,success: t('users.create.success')
    else
      flash.now[:danger] = t('user_sessions.create.failure')
      render :new, status: :unprocessable_entity
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PackingApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <% if logged_in? %>
      <%= render 'shared/header' %>
    <% else %>
      <%= render 'shared/before_login_header' %>
    <% end %>
      <%= render 'shared/flash_message' %>
      <%= yield %>
      <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_before_login_header.html.erb
<header class="text-gray-600 body-font">
  <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
    <a class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">
      <div>
        <%= image_tag 'logo.png', alt: 'Logo', class: 'w-20 h-20 p-2' %>
      </div>
      <span class="ml-3 text-xl">Packing Checker</span>
    </a>
    <nav class="md:ml-auto md:mr-auto flex flex-wrap items-center text-base justify-center">
      <a class="mr-5 hover:text-gray-900"><%= t('header.how_to_use') %></a>
      <a class="mr-5 hover:text-gray-900">
        <%= link_to t('header.login'), login_path, class: "nav-link" %>
      </a>
    </nav>
    <button class="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">プロフィール
    </button>
  </div>
</header>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation" class="alert alert-danger p-6 mb-6 rounded-xl shadow-lg bg-blue-300 text-white font-semibold">
    <ul class="mb-0">
      <% object.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %> p-6 mb-6 rounded-xl shadow-lg bg-blue-300 text-white font-semibold">
    <%= message %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="text-gray-600 body-font">
  <div class="bg-gray-100">
    <div class="container mx-auto py-4 px-5 flex items-center">
      <%= image_tag 'logo.png', alt: 'Logo', class: 'w-40 h-40 p-2' %>
      <h1 class="ml-4">Packing Checkerはみなさんの旅行の準備をお手伝いする、タスク管理アプリです</h1>
    </div>
    <div class="container mx-auto py-4 px-5 flex flex-wrap flex-col sm:flex-row">
      <p class="text-gray-500 text-sm text-center sm:text-left">© 2024 Ikeda Ayato. All Rights Reserved.
        <a href="https://twitter.com/tjalk10251" rel="noopener noreferrer" class="text-gray-600 ml-1" target="_blank">@tjalk10251</a>
      </p>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header class="text-gray-600 body-font">
  <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
    <a class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">
      <div>
        <%= image_tag 'logo.png', alt: 'Logo', class: 'w-20 h-20 p-2' %>
      </div>
      <span>
      <%= link_to "Packing Checker", root_path, class: "ml-3 text-xl text-black" %>
      </span>
    </a>
    <nav class="md:ml-auto md:mr-auto flex flex-wrap items-center text-base justify-center">
      <%= link_to t('header.create_travel_plan'), new_travel_plan_path, class: "mr-5 hover:text-gray-900" %>
      <%= link_to t('header.travel_plan_index'), travel_plans_path, class: "mr-5 hover:text-gray-900" %>
      <a class="mr-5 hover:text-gray-900"><%= t('header.tip') %></a>
      <a class="mr-5 hover:text-gray-900"><%= t('header.how_to_use') %></a>
      <%= link_to t('header.logout'), logout_path, class: "mr-5 hover:text-gray-900", data: { turbo_method: :delete } %>
    </nav>
    <button class="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">
      <%= t('header.profile') %>
    </button>
  </div>
</header>

app/views/shared/_search_form.html.erb
<%= search_form_for @q, url: travel_plan_tasks_path(@travel_plan), method: :get, class: 'form-inline' do |f| %>
  <a class="d-flex">
    <a class="me-2">
      <%= f.select :baggage_eq, options_for_select([['手荷物', 'carry'], ['預け荷物', 'leave']], selected: @q.baggage_eq), { include_blank: 'すべて' } %>
    </a>
    <a class="me-2">
      <%= f.select :status_eq, options_for_select([['保留中', 'pending'], ['実行中', 'working'], ['完了', 'done']], selected: @q.status_eq), { include_blank: 'すべて' } %>
    </a>
    <input type="submit" value="<%= t('tasks.index.search') %>" class="btn btn-outline-success">
  </a>
<% end %>

app/views/static_pages/top.html.erb
<section class="text-gray-600 body-font">
  <div class="container flex px-5 py-24 md:flex-row flex-col items-center">
    <div class="lg:flex-grow md:w-1/2 lg:pr-24 md:pr-16 flex flex-col md:items-start md:text-left mb-16 md:mb-0 items-center text-center">
      <h1 class="title-font sm:text-4xl text-3xl mx-auto mb-4 font-medium text-gray-900">Packing Checkerを利用して</h1>
      <h1 class="title-font sm:text-4xl text-3xl mx-auto mb-4 font-medium text-gray-900">後悔のない思い出作りを</h1>
      <p class="mb-8 mx-auto leading-relaxed">海外旅行、なにをもっていけばいいのか、また飛行機に何を持ち込んで良くて、</p>
      <p class="mb-8 mx-auto leading-relaxed">何を持ち込んではいけないのか。調べ準備するだけでもかなり大変です。</p>
      <p class="mb-8 mx-auto leading-relaxed">Packing Checkerにぜひお手伝いさせてください。</p>
      <div class="mx-auto">
        <%= link_to "荷造りをする", new_travel_plan_path, class: "ml-4 inline-flex text-gray-700 bg-gray-100 border-0 py-2 px-6 focus:outline-none hover:bg-gray-200 rounded text-lg" %>
      </div>
    </div>
    <div class="lg:max-w-lg lg:w-full md:w-1/2 w-5/6">
      <%= image_tag 'seaside.jpg', class: 'object-cover object-center rounded', alt: 'hero' %>
    </div>  
  </div>
</section>

app/views/tasks/_form.html.erb
<%= form_with model: [@travel_plan, @task] do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="p-2 w-full">
    <div class="relative">
      <div class="mb-3">
        <%= f.label t('activerecord.attributes.task.title') %>
        <%= f.text_field :title, class: "w-full bg-gray-100 bg-opacity-50 rounded border border-gray-300 focus:border-indigo-500 focus:bg-white focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out" %>
      </div>
    </div>
  </div>
  <div class="p-2 w-full">
    <div class="relative">
      <div class="mb-3">
        <%= f.label t('activerecord.attributes.task.baggage_type'), class: "leading-7 text-sm text-gray-600" %>
        <%= f.select :baggage, options_for_select([['手荷物', 'carry'], ['預け荷物', 'leave']], selected: @task.baggage) %>
      </div>
    </div>
  </div>
  <div class="p-2 w-full">
    <div class="relative">
      <div class="mb-3">
        <%= f.label t('activerecord.attributes.task.body'), class: "leading-7 text-sm text-gray-600" %>
        <%= f.text_area :body, class: "w-full bg-gray-100 bg-opacity-50 rounded border border-gray-300 focus:border-indigo-500 focus:bg-white focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out" %>
      </div>
    </div>
  </div>
  <div class="p-2 w-full">
    <div class="relative">
      <div class="mb-3">
        <%= f.label t('activerecord.attributes.task.status_type'), class: "leading-7 text-sm text-gray-600" %>
        <%= f.select :status, options_for_select([['保留中', 'pending'], ['実行中', 'working'],['完了', 'done']], selected: @task.status) %>
      </div>
    </div>
  </div>
  <div class="p-2 w-full">
    <%= f.submit nil, class: "flex mx-auto text-white bg-indigo-500 border-0 py-2 px-8 focus:outline-none hover:bg-indigo-600 rounded text-lg" %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<section>
  <div class="relative z-10 container mx-auto flex px-5 py-24 md:flex-row flex-col items-center">
    <div class="flex flex-col text-center w-full mb-12">
      <h1 class="title-font sm:text-4xl text-3xl mb-12 font-medium text-gray-900">
        <%= t('.subject') %>
      </h1>
      <div class="lg:w-1/2 md:w-2/3 mx-auto">
        <div class="flex-wrap -m-2">
          <%= render 'form', task: @task %>
        </div>
      </div>
    </div>
    <div class="lg:max-w-lg lg:w-full md:w-1/2 w-5/6">
      <h2>荷造りのコツ</h2>
      <p>• まずはリストを作成する。</p>
      <p>• 必要最低限の荷物を厳選する。</p>
      <p>• パッキング時にはスペースを有効活用する。</p>
    </div>
  </div>
</section>

app/views/tasks/index.html.erb
<section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto">
    <div class="flex flex-col text-center w-full mb-20">
      <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900"><%= @travel_plan.title %></h1>
      <p class="lg:w-2/3 mx-auto leading-relaxed text-base"><%= @travel_plan.note %></p>
      <p class="lg:w-2/3 mx-auto leading-relaxed text-base">
        <%= link_to t('.create_task'), new_travel_plan_task_path, class: "mr-5 hover:text-gray-900" %>
      </p>
    </div>
    <div class="lg:w-2/3 w-full mx-auto overflow-auto">
      <%= render 'shared/search_form' %>
      <table class="table-auto w-full text-left whitespace-no-wrap ">
        <thead>
          <tr>
            <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl"><%= t('activerecord.attributes.task.title') %></th>
            <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100"><%= t('activerecord.attributes.task.body') %></th>
            <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100"><%= t('activerecord.attributes.task.baggage_type') %></th>
            <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100"><%= t('helpers.submit.edit') %></th>
            <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100"><%= t('helpers.submit.delete') %></th>
            <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tr rounded-br"><%= t('activerecord.attributes.task.status_type') %></th>
          </tr>
        </thead>
        <tbody>
          <% @tasks.each do |task| %>
            <tr>
              <td class="px-4 py-3"><%= task.title %></td>
              <td class="px-4 py-3"><%= task.body %></td>
              <td class="px-4 py-3"><%= t("activerecord.attributes.task.baggage.#{task.baggage}") %></td>
              <td class="px-4 py-3"><%= link_to t('helpers.submit.edit'), edit_travel_plan_task_path(@travel_plan, task) %></td>
              <td class="px-4 py-3"><%= link_to t('helpers.submit.delete'), travel_plan_task_path(@travel_plan, task), data: { turbo_method: :delete } %></td>
              <td class="px-4 py-3"><%= t("activerecord.attributes.task.status.#{task.status}") %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <%= paginate @tasks %>
  </div>
</section>

app/views/tasks/new.html.erb
<section>
  <div class="relative z-10 container mx-auto flex px-5 py-24 md:flex-row flex-col items-center">
    <div class="flex flex-col text-center w-full mb-12">
      <h1 class="title-font sm:text-4xl text-3xl mb-12 font-medium text-gray-900">
        <%= t('.subject') %>
      </h1>
      <div class="lg:w-1/2 md:w-2/3 mx-auto">
        <div class="flex-wrap -m-2">
          <%= render 'form', task: @task %>
        </div>
      </div>
    </div>
    <div class="lg:max-w-lg lg:w-full md:w-1/2 w-5/6">
      <h2>荷造りのコツ</h2>
      <p>• まずはリストを作成する。</p>
      <p>• 必要最低限の荷物を厳選する。</p>
      <p>• パッキング時にはスペースを有効活用する。</p>
    </div>
  </div>
</section>

app/views/travel_plans/_form.html.erb
<%= form_with model: travel_plan do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="p-2 w-full">
    <div class="relative">
      <div class="mb-3">
        <%= f.label :title %>
        <%= f.text_field :title, class: "w-full bg-gray-100 bg-opacity-50 rounded border border-gray-300 focus:border-indigo-500 focus:bg-white focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out" %>
      </div>
    </div>
  </div>
  <div class="p-2 w-full">
    <div class="relative">
      <div class="mb-3">
          <%= f.label :country, class: "leading-7 text-sm text-gray-600" %>
          <%= f.text_field :country, class: "w-full bg-gray-100 bg-opacity-50 rounded border border-gray-300 focus:border-indigo-500 focus:bg-white focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out" %>
      </div>
    </div>
  </div>
  <div class="p-2 w-full">
    <div class="relative">
      <div class="mb-3">
        <%= f.label :note, class: "leading-7 text-sm text-gray-600" %>
        <%= f.text_area :note, class: "w-full bg-gray-100 bg-opacity-50 rounded border border-gray-300 focus:border-indigo-500 focus:bg-white focus:ring-2 focus:ring-indigo-200 h-32 text-base outline-none text-gray-700 py-1 px-3 resize-none leading-6 transition-colors duration-200 ease-in-out" %>
      </div>
    </div>
  </div>
  <div class="p-2 w-full">
    <div class="relative">
      <div class="mb-3">
        <%= f.label :due, class: "leading-7 text-sm text-gray-600" %>
        <%= f.date_field :due, class: "w-full bg-gray-100 bg-opacity-50 rounded border border-gray-300 focus:border-indigo-500 focus:bg-white focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out" %>
      </div>
    </div>
  </div>
  <div class="p-2 w-full">
    <%= f.submit nil, class: "flex mx-auto text-white bg-indigo-500 border-0 py-2 px-8 focus:outline-none hover:bg-indigo-600 rounded text-lg" %>
  </div>
<% end %>

app/views/travel_plans/_travel_plan.html.erb
<div class="p-4 md:w-1/3">
  <div class="flex rounded-lg h-full bg-gray-100 p-8 flex-col">
    <a class="inline-flex sm:ml-auto sm:mt-0 justify-center sm:justify-start">
      <h4>出発日：</h4>
      <%= travel_plan.due %>
    </a>
    <div class="flex items-center mb-3">
      <div class="w-12 h-12 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 mb-5">
        <%= image_tag 'airplane.png'%>
      </div>
      <span class="text-gray-900 text-lg title-font font-medium px-8">
        <%= link_to travel_plan.title, travel_plan_tasks_path(travel_plan) %>
      </span>
    </div>
    <div class="flex-grow">
      <p class="leading-relaxed text-base">
        <%# travel_plan.note が存在しない場合でもスペースを確保 %>
        <%= travel_plan.note.presence || '&nbsp;'.html_safe %> 
      </p>
      <div class="mt-3 text-indigo-500 flex justify-between">
        <%= link_to t('travel_plans.index.create_task'), new_travel_plan_task_path(travel_plan) %>
        <div class="flex ml-auto space-x-4">
          <%= link_to t('helpers.submit.edit'), edit_travel_plan_path(travel_plan) %>
          <%= link_to t('helpers.submit.delete'), travel_plan_path(travel_plan), data: { turbo_method: :delete } %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/travel_plans/index.html.erb
<section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto">
    <div class="flex flex-col text-center w-full mb-20">
      <h2 class="text-xs text-indigo-500 tracking-widest font-medium title-font mb-1">さあ旅路をはじめよう</h2>
      <h1 class="sm:text-3xl text-2xl font-medium title-font text-gray-900">TRAVEL PLAN LIST</h1>
    </div>
    <div class="flex flex-wrap -m-4">
      <%= render @travel_plans %>
    </div>
    <%= paginate @travel_plans %>
  </div>
</section>

app/views/travel_plans/new.html.erb
<section class="text-gray-600 body-font">
  <div class="container mx-auto flex px-5 py-24 md:flex-row flex-col items-center">
    <div class="flex flex-col text-center w-full mb-12">
      <h1 class="title-font sm:text-4xl text-3xl mb-12 font-medium text-gray-900">
        <%= t('.subject') %>
      </h1>
      <div class="lg:w-1/2 md:w-2/3 mx-auto">
        <div class="flex-wrap -m-2">
          <%= render 'form', travel_plan: @travel_plan %>
        </div>
      </div>
    </div>
    <div class="lg:max-w-lg lg:w-full md:w-1/2 w-5/6">
      <%= image_tag 'travel_girl.png', class:"object-cover object-center rounded" %>
    </div>
  </div>
</section>

app/views/user_sessions/new.html.erb
<section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto flex flex-wrap items-center">
    <div class="lg:w-3/5 md:w-1/2 md:pr-16 lg:pr-0 pr-0">
      <h1 class="title-font font-medium text-3xl text-gray-900">Slow-carb next level shoindcgoitch ethical authentic, poko scenester</h1>
      <p class="leading-relaxed mt-4">Poke slow-carb mixtape knausgaard, typewriter street art gentrify hammock starladder roathse. Craies vegan tousled etsy austin.</p>
    </div>
    <div class="lg:w-2/6 md:w-1/2 bg-gray-100 rounded-lg p-8 flex flex-col md:ml-auto w-full mt-10 md:mt-0">
      <%= form_with model: @user do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <div class="relative mb-4">
          <%= f.label :email, class: "form-label" %>
          <%= f.email_field :email, class: "w-full bg-white rounded border border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out" %>
        </div>
        <div class="relative mb-4">
          <%= f.label :password, class: "form-label" %>
          <%= f.password_field :password, class: "w-full bg-white rounded border border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out" %>
        </div>
        <%= f.submit t('.login'), class: "text-white bg-indigo-500 border-0 py-2 px-8 focus:outline-none hover:bg-indigo-600 rounded text-lg"%>
        <div class="text-xs text-gray-500 mt-3">
          <%= link_to t('.to_register_page'), new_user_path %>
        </div>
      <% end %>
    </div>
  </div>
</section>